//
//  WeatherDetailPresenter.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherDetailPresentationLogic
{
    func presentWeather(response: WeatherDetail.Response)
}

class WeatherDetailPresenter: WeatherDetailPresentationLogic
{
    weak var viewController: WeatherDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentWeather(response: WeatherDetail.Response)
    {
        let forcastItem = response.forcastItem
        let location = forcastItem.name ?? ""
        let temperature = forcastItem.main?.temp ?? 0
        let humidity = forcastItem.main?.humidity ?? 0
        let viewModel = WeatherDetail.ViewModel.DisplayWeather(location: location, temperature: temperature, humidity: humidity)
        viewController?.displayWeather(viewModel: viewModel)
    }
}
