//
//  WeatherDetailInteractor.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WeatherDetailBusinessLogic
{
    func getWeather(request: WeatherDetail.Request.GetWeather)
}

protocol WeatherDetailDataStore
{
    var forecastItem: ForecastItem? { get set }
}

class WeatherDetailInteractor: WeatherDetailBusinessLogic, WeatherDetailDataStore
{
    var forecastItem: ForecastItem?
    var presenter: WeatherDetailPresentationLogic?
    var worker: WeatherDetailWorker?
    
    // MARK: Do something
    
    func getWeather(request: WeatherDetail.Request.GetWeather)
    {
        if let forecastItem = forecastItem {
            let response = WeatherDetail.Response(forcastItem: forecastItem)
            presenter?.presentWeather(response: response)
        }
    }
}
