//
//  LocationSearchInteractorTests.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import WeatherForecast
import XCTest

class LocationSearchInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: LocationSearchInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupLocationSearchInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupLocationSearchInteractor()
  {
    sut = LocationSearchInteractor()
  }
  
  // MARK: Test doubles
  
  class LocationSearchPresentationLogicSpy: LocationSearchPresentationLogic
  {
    var presentWeatherDetailCalled = false
    var presentErrorCalled = false

    func presentWeatherDetail(response: LocationSearch.Response.FetchCurrentWeather) {
        presentWeatherDetailCalled = true
    }
    
    func presentError(error: WeatherError) {
        presentErrorCalled = true
    }
  }
  
  // MARK: Tests
  
  func testFetchCurrentWeather()
  {
    // Given
    let spy = LocationSearchPresentationLogicSpy()
    sut.presenter = spy
    let request = LocationSearch.Request.FetchCurrentWeather(location: "")
    
    // When
    sut.fetchCurrentWeather(request: request)
    
    // Then
    XCTAssertTrue(spy.presentWeatherDetailCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
