//
//  LocationSearchInteractorTests.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import WeatherForecast
import XCTest

class LocationSearchInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: LocationSearchInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupLocationSearchInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupLocationSearchInteractor()
  {
    sut = LocationSearchInteractor()
  }
  
  // MARK: Test doubles
  
  class LocationSearchPresentationLogicSpy: LocationSearchPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: LocationSearch.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = LocationSearchPresentationLogicSpy()
    sut.presenter = spy
    let request = LocationSearch.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
