//
//  LocationSearchPresenter.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationSearchPresentationLogic
{
    func presentWeatherDetail(response: LocationSearch.Response.FetchCurrentWeather)
    func presentError(error: WeatherError)
}

class LocationSearchPresenter: LocationSearchPresentationLogic
{
    
    weak var viewController: LocationSearchDisplayLogic?
    
    // MARK: Do something
    
    func presentWeatherDetail(response: LocationSearch.Response.FetchCurrentWeather)
    {
        let weather = response.forcastItem
        let location = weather.name ?? ""
        let temperature = weather.main?.temp ?? 0
        let humidity = weather.main?.humidity ?? 0
        let viewModel = LocationSearch.ViewModel.Weather(location: location, temperature: temperature, humidity: humidity)
        viewController?.displayWeatherDetail(viewModel: viewModel)
    }
    
    func presentError(error: WeatherError) {
        viewController?.displayAlertMessage(viewModel: LocationSearch.ViewModel.Error(message: error.localizedDescription))
    }
}
