//
//  LocationSearchWorker.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class LocationSearchWorker
{
    func fetchCurrentWeather(location: String, completionHandler: @escaping (WeatherStoreResult) -> Void)
    {
        let service = WeatherAPI.getCurrentWeatherByCityName(location: location)
        APIHelper.getRequesterDefault(service: service) { result in
            switch result {
            case let .success(moyaResponse):
                if let responseMapper: ForecastItem = APIHelper.parseDataResponse(data: moyaResponse.data) {
                    completionHandler(WeatherStoreResult.forecastItem(responseMapper))
                }
                else {
                    completionHandler(WeatherStoreResult.error(WeatherError.unknown))
                }
            case let .failure(error):
                let _error: WeatherError!
                switch error {
                case let .encodableMapping(error): _error = WeatherError.encodableMapping(error)
                case let .underlying(error, _): _error = WeatherError.underlying(error)
                default: _error = WeatherError.unknown
                }
                completionHandler(WeatherStoreResult.error(_error))
            }
        }
    }
}
