//
//  LocationSearchRouter.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//enum SegueLocationSearch: String {
//    case showWeatherDetail = "SegueLocationSearchShowWeatherDetail"
//}

protocol LocationSearchRoutingLogic
{
    func routeToWeatherDetail(segue: UIStoryboardSegue?)
}

protocol LocationSearchDataPassing
{
    var dataStore: LocationSearchDataStore? { get }
}

class LocationSearchRouter: NSObject, LocationSearchRoutingLogic, LocationSearchDataPassing
{
    weak var viewController: LocationSearchViewController?
    var dataStore: LocationSearchDataStore?
    
    // MARK: Routing
    
    func routeToWeatherDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! WeatherDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToWeatherDetail(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "WeatherDetailViewController") as! WeatherDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToWeatherDetail(source: dataStore!, destination: &destinationDS)
            navigateToWeatherDetail(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToWeatherDetail(source: LocationSearchViewController, destination: WeatherDetailViewController)
    {
//        source.performSegue(withIdentifier: SegueLocationSearch.showWeatherDetail.rawValue, sender: nil)
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToWeatherDetail(source: LocationSearchDataStore, destination: inout WeatherDetailDataStore)
    {
        destination.forecastItem = source.forecastItem
    }
}
