//
//  LocationSearchModels.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LocationSearch
{    
    struct Request
    {
        struct FetchCurrentWeather
        {
            let location: String
        }
    }
    struct Response
    {
        struct FetchCurrentWeather {
            var forcastItem: ForecastItem
        }
    }
    struct ViewModel
    {
        struct Weather
        {
            let location: String
            let temperature: Float
            let humidity: Int
        }
        struct Error
        {
            let message: String
        }
    }
}
