//
//  ConfirmPinInteractor.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 8/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfirmPinBusinessLogic
{
  func doSomething(request: ConfirmPin.Something.Request)
}

protocol ConfirmPinDataStore
{
  //var name: String { get set }
}

class ConfirmPinInteractor: ConfirmPinBusinessLogic, ConfirmPinDataStore
{
  var presenter: ConfirmPinPresentationLogic?
  var worker: ConfirmPinWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ConfirmPin.Something.Request)
  {
    worker = ConfirmPinWorker()
    worker?.doSomeWork()
    
    let response = ConfirmPin.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
