//
//  ConfirmPinPresenter.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 8/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ConfirmPinPresentationLogic
{
  func presentSomething(response: ConfirmPin.Something.Response)
}

class ConfirmPinPresenter: ConfirmPinPresentationLogic
{
  weak var viewController: ConfirmPinDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ConfirmPin.Something.Response)
  {
    let viewModel = ConfirmPin.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
