//
//  LocationSearchInteractor.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationSearchBusinessLogic
{
  func doSomething(request: LocationSearch.Something.Request)
}

protocol LocationSearchDataStore
{
  //var name: String { get set }
}

class LocationSearchInteractor: LocationSearchBusinessLogic, LocationSearchDataStore
{
  var presenter: LocationSearchPresentationLogic?
  var worker: LocationSearchWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LocationSearch.Something.Request)
  {
    worker = LocationSearchWorker()
    worker?.doSomeWork()
    
    let response = LocationSearch.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
