//
//  LocationSearchViewController.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationSearchDisplayLogic: class
{
    func displaySomething(viewModel: LocationSearch.Something.ViewModel)
}

class LocationSearchViewController: UIViewController, LocationSearchDisplayLogic
{
    
    @IBOutlet weak var oLabelTitle: UILabel!
    @IBOutlet weak var oTextFieldSearch: UITextField!
    @IBOutlet weak var oButtonSearch: UIButton!
    
    var interactor: LocationSearchBusinessLogic?
    var router: (NSObjectProtocol & LocationSearchRoutingLogic & LocationSearchDataPassing)?
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = LocationSearchInteractor()
        let presenter = LocationSearchPresenter()
        let router = LocationSearchRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = LocationSearch.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: LocationSearch.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    @IBAction func pressButton(_ sender: Any) {
    }
}
