//
//  LocationSearchPresenter.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 6/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LocationSearchPresentationLogic
{
  func presentSomething(response: LocationSearch.Something.Response)
}

class LocationSearchPresenter: LocationSearchPresentationLogic
{
  weak var viewController: LocationSearchDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: LocationSearch.Something.Response)
  {
    let viewModel = LocationSearch.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
