//
//  ForecastListPresenterTests.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 7/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import WeatherForecast
import XCTest

class ForecastListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ForecastListPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupForecastListPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupForecastListPresenter()
  {
    sut = ForecastListPresenter()
  }
  
  // MARK: Test doubles
  
  class ForecastListDisplayLogicSpy: ForecastListDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: ForecastList.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = ForecastListDisplayLogicSpy()
    sut.viewController = spy
    let response = ForecastList.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
