//
//  ForecastListInteractorTests.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 7/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import WeatherForecast
import XCTest

class ForecastListInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ForecastListInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupForecastListInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupForecastListInteractor()
  {
    sut = ForecastListInteractor()
  }
  
  // MARK: Test doubles
  
  class ForecastListPresentationLogicSpy: ForecastListPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: ForecastList.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = ForecastListPresentationLogicSpy()
    sut.presenter = spy
    let request = ForecastList.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
