//
//  ForecastListModels.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 7/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ForecastList
{
  // MARK: Use cases
  
  enum Forecast
  {
    struct Request
    {
    }
    struct Response
    {
        var location: String
        var weatherList: [ForecastItem]
    }
    struct ViewModel
    {
        var location: String
        var weatherList: [ForecastItem]
    }
  }
}
