//
//  ForecastListInteractor.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 7/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForecastListBusinessLogic
{
    func doSomething(request: ForecastList.Forecast.Request)
}

protocol ForecastListDataStore
{
    var location: String { get set }
}

class ForecastListInteractor: ForecastListBusinessLogic, ForecastListDataStore
{
    var location: String = ""
    var presenter: ForecastListPresentationLogic?
    var worker: ForecastListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: ForecastList.Forecast.Request)
    {
        worker = ForecastListWorker()
        worker?.doSomeWork()
        
        let response = ForecastList.Forecast.Response(location: "", weatherList: [])
        presenter?.presentSomething(response: response)
    }
}
