//
//  ForecastListPresenter.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 7/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ForecastListPresentationLogic
{
  func presentSomething(response: ForecastList.Forecast.Response)
}

class ForecastListPresenter: ForecastListPresentationLogic
{
  weak var viewController: ForecastListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ForecastList.Forecast.Response)
  {
    let viewModel = ForecastList.Forecast.ViewModel(location: response.location, weatherList: response.weatherList)
    viewController?.displayWeatherList(viewModel: viewModel)
  }
}
