//
//  CreatePinInteractor.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 8/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreatePinBusinessLogic
{
  func doSomething(request: CreatePin.Something.Request)
}

protocol CreatePinDataStore
{
  //var name: String { get set }
}

class CreatePinInteractor: CreatePinBusinessLogic, CreatePinDataStore
{
  var presenter: CreatePinPresentationLogic?
  var worker: CreatePinWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CreatePin.Something.Request)
  {
    worker = CreatePinWorker()
    worker?.doSomeWork()
    
    let response = CreatePin.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
