//
//  OTPInteractor.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 8/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OTPBusinessLogic
{
  func doSomething(request: OTP.Something.Request)
}

protocol OTPDataStore
{
  //var name: String { get set }
}

class OTPInteractor: OTPBusinessLogic, OTPDataStore
{
  var presenter: OTPPresentationLogic?
  var worker: OTPWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: OTP.Something.Request)
  {
    worker = OTPWorker()
    worker?.doSomeWork()
    
    let response = OTP.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
