//
//  OTPPresenter.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 8/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OTPPresentationLogic
{
  func presentSomething(response: OTP.Something.Response)
}

class OTPPresenter: OTPPresentationLogic
{
  weak var viewController: OTPDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: OTP.Something.Response)
  {
    let viewModel = OTP.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
