//
//  ResetPasswordInteractor.swift
//  WeatherForecast
//
//  Created by Itsaraporn Chaichayanon on 8/8/18.
//  Copyright (c) 2018 ItsaraChai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ResetPasswordBusinessLogic
{
  func doSomething(request: ResetPassword.Something.Request)
}

protocol ResetPasswordDataStore
{
  //var name: String { get set }
}

class ResetPasswordInteractor: ResetPasswordBusinessLogic, ResetPasswordDataStore
{
  var presenter: ResetPasswordPresentationLogic?
  var worker: ResetPasswordWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ResetPassword.Something.Request)
  {
    worker = ResetPasswordWorker()
    worker?.doSomeWork()
    
    let response = ResetPassword.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
